# Generated by Django 5.2 on 2025-04-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='product_name_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
