# Generated by Django 5.2 on 2025-05-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mealrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
